"""empty message

Revision ID: 4c2ea0072f03
Revises: c6b3a386f119
Create Date: 2023-03-13 15:39:58.470846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2ea0072f03'
down_revision = 'c6b3a386f119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses_scores', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('grade_point',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('scored_point',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('students_records', schema=None) as batch_op:
        batch_op.alter_column('total_points',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('gpa',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students_records', schema=None) as batch_op:
        batch_op.alter_column('gpa',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_points',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('student_courses_scores', schema=None) as batch_op:
        batch_op.alter_column('scored_point',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('grade_point',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
