"""empty message

Revision ID: 686142c4f4e6
Revises: 
Create Date: 2023-03-11 22:53:16.398491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686142c4f4e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code'))
    )
    op.create_table('gradescale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('point', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('min', sa.Integer(), nullable=False),
    sa.Column('max', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gradescale'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Enum('PROF', 'ENGR', 'DR', 'MR', 'MRS', 'MS', name='title'), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('matric_no', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id_users')),
    sa.PrimaryKeyConstraint('student_id', name=op.f('pk_students')),
    sa.UniqueConstraint('matric_no', name=op.f('uq_students_matric_no'))
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('staff_code', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_teachers_user_id_users')),
    sa.PrimaryKeyConstraint('teacher_id', name=op.f('pk_teachers')),
    sa.UniqueConstraint('staff_code', name=op.f('uq_teachers_staff_code'))
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('credit', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_courses_department_id_departments')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_courses_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('code', name=op.f('uq_courses_code'))
    )
    op.create_table('students_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('matric_no', sa.String(length=12), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('course_count', sa.Integer(), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('gpa', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('honurs', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_students_records_department_id_departments')),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('fk_students_records_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students_records'))
    )
    op.create_table('student_courses_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('matric_no', sa.String(length=12), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(length=6), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('grade_point', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('scored_point', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('registered_by', sa.String(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_student_courses_scores_course_id_courses')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_student_courses_scores_department_id_departments')),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('fk_student_courses_scores_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_courses_scores'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_courses_scores')
    op.drop_table('students_records')
    op.drop_table('courses')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('users')
    op.drop_table('gradescale')
    op.drop_table('departments')
    # ### end Alembic commands ###
