"""empty message

Revision ID: d394f2049847
Revises: 11acac9230e4
Create Date: 2023-03-08 17:42:12.802437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd394f2049847'
down_revision = '11acac9230e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(precision=2, asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.Float(precision=1, asdecimal=True), nullable=True))
        batch_op.drop_column('grade_percent')
        batch_op.drop_column('grade_scale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_scale', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('grade_percent', sa.FLOAT(), nullable=True))
        batch_op.drop_column('grade')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
