"""empty message

Revision ID: f5a36722534e
Revises: 4c2ea0072f03
Create Date: 2023-03-17 01:54:03.314311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a36722534e'
down_revision = '4c2ea0072f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gradescale', schema=None) as batch_op:
        batch_op.alter_column('point',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gradescale', schema=None) as batch_op:
        batch_op.alter_column('point',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
